name: Deployment Pipeline

on:
  schedule:
    - cron: '1/15 * * * * *'

jobs:
  scheduled-action:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check health of HerokuAPP
        with:
          url: http://iiigygyiii-pokedex.herokuapp.com/
          follow-redirect: no
          max-attempts: 3
          retry-delay: 10s
